---
shallow_clone: true
platform: x64
install:
  - '"C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" amd64'
  - SET PATH=C:\Ruby%ruby_version%\bin;%PATH%
  - gem update --system
  - gem install hoe minitest rake-compiler --no-document
build_script:
  - cd ext\psych
  - ruby extconf.rb --enable-bundled-libyaml
  - nmake
test_script:
  - rake test
environment:
  matrix:
    - ruby_version: "21-x64"
    - ruby_version: "22-x64"
