name: windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [ '2.6.x', '2.5.x', '2.4.x' ]
    steps:
    - uses: actions/checkout@master
    - name: Set up Ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Update MSYS2
      uses: MSP-Greg/msys2-action@master
      with:
        base: update
    - name: Install dependencies
      run: |
        call gem update --system --no-document --conservative
        bundle install
    - name: Run test
      run: rake
